add flag to report changes anywhere in changed files
golangci/revgrep pull request #6
Opened 2021-09-29 03:31 UTC by natefinch

This adds support needed for https://github.com/golangci/golangci-lint/issues/2261

2021-09-29 16:50 UTC, SVilgelm requested changes

2021-09-29 16:50 UTC, SVilgelm commented on revgrep.go
> +
I recommend to move it to line 118, to report as soon as possible

2021-09-29 18:32 UTC, bombsimon approved these changes
I agree with @SVilgelm to do as early return as possible, other than that LGTM!

2021-09-30 04:13 UTC, natefinch commented
Yeah, I wasn't super clear on what the whole fpos hunkpos stuff was doing, so I figured it was safer to put this at the end where we know we don't have another right answer. But if you think this is still the right answer at line 118, I'm happy to move it.

2021-09-30 12:51 UTC, SVilgelm approved these changes

2021-09-30 12:51 UTC, merged